<div id="container" style="background-size:100%;background-repeat:no-repeat;position: relative;margin-left:60px;margin-right:60px;overflow: hidden;background-image: url(<?php echo $this->getSkinUrl('images/bg_MIAMI.jpg') ?>)">
&nbsp;
</div>

<div class="titolo_boutique_interno">
    <div class="contenuto">
        <h1>Miami</h1>
        <p class="sottotitolo"><?php echo $this->__("uomo") ?> / <span><?php echo $this->__("donna") ?></span></p>
    </div>
</div>
<p class="scroll_down" style="opacity: 1;float: left;width: 100%;margin-top:15px;text-align: center"></p>
<div class="contenuto_boutique_interno">
    <div class="blocco_init visibile">
        <div class="immagine_boutique_interno">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-alta.jpg") ?>" />
        </div>
        <div class="testo_boutique_interno">
            <h3>Brands</h3>
            <ul class="lista_brand_b">
                <?php
                $brands=$this->getListaBrands("Miami");

                for ($i=0; $i<count($brands); $i++){
                    $nome_brands=$brands[$i][1];
                    $slug_brands=$brands[$i][2];
                    $sale=$brands[$i][3];


                    if ($sale=="1"){
                        echo "<li><a href='".Mage::getBaseUrl()."".$slug_brands.".html'>".$nome_brands."</a></li>";
                    }
                    else {
                        echo "<li>$nome_brands</li>";
                    }

                }

                ?>
                <!--<li><a href="#">Caban Romantic</a></li>
                <li><a href="#">Leitmotiv</a></li>
                <li><a href="#">Maria Escote</a></li>
                <li><a href="#">Mr&Mrs Fur</a></li>
                <li><a href="#">P.A.R.O.S.H.</a></li>
                <li><a href="#">Ruthie Davis</a>
                <li><a href="#">Shourouk</a></li>
                <li><a href="#">Stefano De Lellis</a></li>-->
            </ul>
        </div>
    </div>
    <div class="blocco1 visibile">
        <div class="vuoto">
            &nbsp;
        </div>
        <div class="testo">
            <button type="button" name="shop" id="shop" class="shop" onclick="window.location = 'mailto:support@coltortiboutique.com';"><?php echo $this->__("contatta la boutique") ?></button>
        </div>
        <div class="immagine">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-lunga.jpg") ?>" />
        </div>
    </div>
    <div class="blocco2 visibile">
        <div class="immagine">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-coltorti-miami-lunga.jpg") ?>" />
        </div>
        <div class="vuoto">
            &nbsp;
        </div>
    </div>
    <div class="blocco3 visibile">
        <div class="testo">
            <div class="dati">
                <h1>Miami</h1>
                <p class="sottotitolo"><?php echo $this->__("Uomo / Donna") ?></p>
                <p class="indirizzo">1111 Lincoln Road</p>
                <p class="indirizzo">33139 Miami Beach Florida</p>
                <p class="indirizzo">T. +1 786 517 1330</p>
            </div>
        </div>
        <div class="immagine">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-coltorti-lunga.jpg") ?>" />
        </div>
        <div class="vuoto">
            &nbsp;
        </div>
    </div>
    <div class="blocco4 visibile">
        <div class="testo_boutique_interno">
            <div class="cont_testo">
                <p class="titolo"><?php echo $this->__("Orari di apertura") ?></p>
                <table>
                    <tr>
                        <td>L.</td><td>11:00 - 21:00</td>
                    </tr>
                    <tr>
                        <td>M.</td><td>11:00 - 21:00</td>
                    </tr>
                    <tr>
                        <td>M.</td><td>11:00 - 21:00</td>
                    </tr>
                    <tr>
                        <td>G.</td><td>11:00 - 21:00</td>
                    </tr>
                    <tr>
                        <td>V.</td><td>11:00 - 22:00</td>
                    </tr>
                    <tr>
                        <td>S.</td><td>11:00 - 22:00</td>
                    </tr>
                    <tr>
                        <td>D.</td><td>12:00 - 21:00</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="immagine_boutique_interno">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-alta-bottom.jpg") ?>" />
        </div>
    </div>
    <div class="blocco5 visibile">
        <div class="immagine">
            <div id="container_macerata" class="cont_boutique">
                <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-lunga-bottom.jpg") ?>" />
            </div>
        </div>
    </div>
    <div class="blocco9 visibile">
        <div class="immagine">
            <img alt="Boutique Miami" title="Boutique Miami"  src="<?php echo $this->getSkinUrl("images/boutiques/miami/boutique-miami-bottom.jpg") ?>" />
        </div>
    </div>
    <div class="blocco7 visibile">
        <div class="testo">
            <div class="link_boutique_social">
                <a href="#" class="first">Facebook</a>
                <a href="#">Twitter</a>
                <a href="#">Instagram</a>
                <a href="#">Pinterest</a>
            </div>
        </div>
    </div>
</div>




