<div class="blocco4 visibile">
    <div id="block41">
            <div class="testo">
                <span class="titolo">DONNA</span>
            </div>
    </div>
    <div id="block42" class="grid">
        <?php $cat=Mage::getModel('catalog/category')->load("4"); ?>

        <figure class="effect-bubba">
            <img alt="Abbigliamento Donna Coltorti Boutique" title="Abbigliamento Donna Coltorti Boutique" src="<?php echo $this->getSkinUrl('images/home/abbigliamento_donna.jpg') ?>"  />
            <figcaption>
                <p>SHOP NOW</p>
                <a href="<?php echo $cat->getUrl() ?>">SHOP NOW</a>
            </figcaption>
        </figure>

        <div class="testo"><span><?php echo $this->__("ABBIGLIAMENTO") ?></span></div>
    </div>
    <div id="block43" class="grid">
        <?php $cat=Mage::getModel('catalog/category')->load("57"); ?>
        <figure class="effect-bubba">
            <img alt="Borse Donna Coltorti Boutique" title="Borse Donna Coltorti Boutique" src="<?php echo $this->getSkinUrl('images/home/bags_donna.jpg') ?>"  />
            <figcaption>
                <p>SHOP NOW</p>
                <a href="<?php echo $cat->getUrl() ?>">SHOP NOW</a>
            </figcaption>
        </figure>
        <div class="testo"><span><?php echo $this->__("BORSE") ?></span></div>
    </div>
    <div id="block44" class="grid">
        <?php $cat=Mage::getModel('catalog/category')->load("18"); ?>
        <figure class="effect-bubba">
            <img alt="Calzature Donna Coltorti Boutique" title="Calzature Donna Coltorti Boutique" src="<?php echo $this->getSkinUrl('images/home/shoes_donna.jpg') ?>"  />
            <figcaption>
                <p>SHOP NOW</p>
                <a href="<?php echo $cat->getUrl() ?>">SHOP NOW</a>
            </figcaption>
        </figure>
        <div class="testo"><span><?php echo $this->__("CALZATURE") ?></span></div>
    </div>
    <div class="block_vuoto">
        &nbsp;
    </div>
</div>