<div class="blocco3 visibile">
    <div id="block31">
        <div class="filosofia">
            <p>The original selection of products from the best brand-names on the market, along with appropriate style consultancy, form the identity of this company, which has become a reference point for the fashion world.</p>
                <p>With their long-standing capacity for interpreting market trends, Coltorti staff accompany visitors to the boutique along an experiential path, to define a unique and personally-adapted style.</p>
                <p>The areas of the boutique encapsulate Coltorti’s contemporary style, with linear shapes and high-class materials giving a sophisticated, refined atmosphere.</p>
                <p>Coltorti is present in Italy with five boutiques: Jesi, Ancona, San Benedetto del Tronto, Macerata and the most recent, opened in 2015, in Pescara. Since 2010, Coltorti is also present in Miami, United States.</p>
        </div>
    </div>
    <div id="block32">
        <div class="coltorti">
            <span class="titolo">COLTORTI</span>
            <span class="sottotitolo">Passion, experience, dynamism and innovation. Coltorti is the perfect interpretation of contemporary prêt-à-porter.</span>
        </div>
    </div>
    <div id="block33">
        <img alt="Logo Coltorti" title="Logo Coltorti" src="<?php echo $this->getSkinUrl("images/home/boutiques-coltorti.jpg") ?>" id="img_boutique">
    </div>
</div>