<div class="blocco1 visibile">
    <div id="block11">
        <div class="designers">
            <div class="testo">
                <span class="titolo">BRANDS</span>
                <button type="button" name="discover" class="button_secondary" value="Discover" onclick="window.location='<?php echo Mage::getBaseUrl()."brands" ?>'"><?php echo $this->__("Discover") ?></button>
                <p class="contenuto"><?php echo $this->__("The best national and international brands, selected to be interpreted in an oblique, personal way, in a contemporary view of the concept of luxury.") ?></p>
            </div>
        </div>
    </div>
    <div id="block12">
        <img alt="Brands Coltorti Boutique" title="Brands Coltorti Boutique" src="<?php echo $this->getSkinUrl("images/home/designer-coltorti-ancona.jpg") ?>" id="img_designer">
    </div>
</div>