<div class="blocco3 visibile">
    <div id="block31">
        <div class="filosofia">
            <p> L’originale selezione dei migliori brand e l’adeguata consulenza stilistica costituiscono l’identità dell’azienda, riconosciuta come punto di riferimento nel mondo del fashion.</p>
            <p>Da sempre in grado di interpretare le tendenze, lo Staff Coltorti accompagna gli ospiti della boutique in un percorso esperienziale, per definire uno stile unico e caratterizzante.</p>
            <p>Gli spazi delle boutique sintetizzano lo stile contemporaneo di Coltorti; forme lineari e materiali di prestigio, per un’atmosfera ricercata e sofisticata.</p>
            <p>Coltorti è presente nel centro Italia con cinque boutiques: Jesi, Ancona, San Benedetto del Tronto, Macerata e la più recente, aperta nel 2015, a Pescara. Dal  2010, Coltorti  è anche a Miami, negli Stati Uniti.</p>
        </div>
    </div>
    <div id="block32">
        <div class="coltorti">
            <span class="titolo">COLTORTI</span>
            <span class="sottotitolo">Passione, esperienza, dinamismo, innovazione e servizio.<br>Coltorti è
                    la perfetta interpretazione del prêt-à-por ter
                    contemporaneo</span>
        </div>
    </div>
    <div id="block33">
        <img alt="Logo Coltorti" title="Logo Coltorti" src="<?php echo $this->getSkinUrl("images/home/boutiques-coltorti.jpg") ?>" id="img_boutique">
    </div>
</div>