<script>
function iedetect(v) {

    var r = RegExp('msie' + (!isNaN(v) ? ('\\s' + v) : ''), 'i');
    return r.test(navigator.userAgent);

}

function GetCookie(name) {
    var arg = name + "=";
    var alen = arg.length;
    var clen = document.cookie.length;
    var i = 0;
    while (i < clen) {
        var j = i + alen;
        if (document.cookie.substring(i, j) == arg)
            return "here";
        i = document.cookie.indexOf(" ", i) + 1;
        if (i == 0) break;
    }
    return null;
}

jQuery(window).load(function () {
    /*video = document.getElementById('video_home2');
     var visit = GetCookie("ZZZZZ");*/

    jQuery(".main-container").css("display", "block");
    jQuery(".footer-container").css("display", "block");

    $width = jQuery(window).width(); // Width of the screen
    altezzaWindow = jQuery(window).height(); // Height of the screen

    /*if (visit == null && jQuery(window).width()>770) {
     jQuery('html').animate({scrollTop: 0}, 1);
     jQuery('body').animate({scrollTop: 0}, 1);

     var $width, $height, // Width and height of screen
     $vidwidth = this.videoWidth, // Width of video (actual width)
     $vidheight = this.videoHeight, // Height of video (actual height)
     // Create function called adjSize

     $height=altezzaWindow;
     $height = $height - 170;


     // Set the container to be the width and height of the screen
     jQuery('#container').css({
     'width': '70%',
     'height': $height + 'px'
     });

     $width = $width - 120;
     $altezzaVideo = jQuery("video").height();
     $marginTop = -($altezzaVideo - $height);

     $vid = jQuery('#container video').css({'width': $width + 'px'});


     video.addEventListener("ended", function () {
     jQuery("#container").fadeOut("slow");
     jQuery(".skip_intro").fadeOut("slow");
     setTimeout(function () {
     jQuery("body").css("overflow", "auto").delay(600);
     jQuery(".menu-link").css("display", "block");
     //jQuery(".skip-links").css("display", "block");
     adatta();
     caricaSlider(altezzaWindow);
     }, 600);
     }, false);

     jQuery(".skip_intro").click(function () {
     jQuery("#video_home2")[0].pause();
     jQuery("#container").fadeOut("slow");
     jQuery(".skip_intro").fadeOut("slow");
     setTimeout(function () {
     jQuery("body").css("overflow", "auto").delay(600);
     jQuery(".menu-link").css("display", "block");
     //jQuery(".skip-links").css("display", "block");
     adatta();
     caricaSlider(altezzaWindow);
     }, 600);

     });

     video.load();
     video.play();

     var expire = new Date();
     expire = new Date(expire.getTime() + 60 * 60 * 1000);
     document.cookie = "ZZZZZ=here; expires=" + expire;
     }
     else {*/
    /*jQuery(".cont_video").remove();
     jQuery(".skip_intro").remove();*/
    jQuery("body").css("overflow", "auto").delay(600);
    jQuery(".menu-link").css("display", "block");
    //jQuery(".skip-links").css("display", "block");
    adatta();
    caricaSlider(altezzaWindow);
    if(window.location.hash) {
        var target_offset = jQuery("#yps").offset();
        var target_top = target_offset.top;


        jQuery('html').animate({scrollTop: target_top}, 1);
        jQuery('body').animate({scrollTop: target_top}, 1);
    }
    //}





    jQuery(window).resize(function () {
        adatta();
        caricaSliderResize();
    });

    jQuery( window ).scroll(function() {
        if (jQuery(document).scrollTop()<=0){
            jQuery( ".scroll_down").css("opacity","1");
        }
        else {
            jQuery( ".scroll_down").css("opacity","0");
        }

    });
});



function caricaSliderResize() {
    height = jQuery(window).height();
    altezza = height - 170;
    jQuery(".bx-wrapper").css("height", altezza + "px");
    jQuery(".bx-viewport").css("height", altezza + "px");
    jQuery(".bxslider li").css("height", altezza + "px");
    jQuery(".bxslider li").find("img").css("height", altezza + "px");

    larghezza = (1920 * altezza) / 960;



    if (jQuery(window).width()>1400) {
        larghTesto = [0,150, 874, 518, 745, 815];
        altTesto = [0,80, 164, 164, 164, 164];
    }
    else {
        larghTesto = [0,10, 600, 421, 524, 498];
        altTesto = [0,150, 164, 164, 164, 164];
    }
    i = 0;
    jQuery(".bxslider li").each(function () {
        alt = altTesto[i];
        marginTop = -(((altezza - alt) / 2) + alt);
        jQuery(this).find(".content-slider-bx").css("margin-top", marginTop + "px");

        larg = larghTesto[i];
        marginLeft = (larghezza - larg) / 2;
        jQuery(this).find(".content-slider-bx").css("margin-left", marginLeft + "px");
        i = i + 1;
    });


    jQuery(".div_slider").css("width", larghezza + "px");

    padding = (altezza - 62) / 2;
    jQuery(".bx-pager").css("padding-top", padding + "px");
}

function caricaSlider(height) {
    altezza = height - 170;
    jQuery(".bx-wrapper").css("height", altezza + "px");
    jQuery(".bx-viewport").css("height", altezza + "px");
    jQuery(".bxslider li").css("height", altezza + "px");
    jQuery(".bxslider li").find("img").css("height", altezza + "px");

    larghezza = jQuery(".img_slider").width();

    /*if (jQuery(window).width()>1400) {
     larghTesto = [-150, 874, 518, 745, 815];
     altTesto = [80, 164, 164, 164, 164];
     }
     else {
     larghTesto = [10, 609, 421, 524, 498];
     altTesto = [150, 164, 164, 164, 164];
     }*/
    if (jQuery(window).width()>1400) {
        larghTesto = [0,-150, 1300,1000,700,682];
        altTesto = [0,80, 80,80,315,35];
    }
    else {
        larghTesto = [0,10, 800,800,500,346];
        altTesto = [0,150, 150,150,209,35];
    }
    i = 0;
    jQuery(".bxslider li").each(function () {
        if (i==2){
            alt = altTesto[i];
            //alt = jQuery(this).find(".content-slider-bx").height();
            marginTop = -(((altezza + alt) / 2));
            jQuery(this).find(".content-slider-bx").css("margin-top", marginTop + "px");
        }
        else {
            alt = altTesto[i];
            //alt = jQuery(this).find(".content-slider-bx").height();
            marginTop = -(((altezza - alt) / 2) + alt);
            jQuery(this).find(".content-slider-bx").css("margin-top", marginTop + "px");
        }

        larg = larghTesto[i];
        marginLeft = (larghezza - larg) / 2;
        jQuery(this).find(".content-slider-bx").css("margin-left", marginLeft + "px");
        i = i + 1;
    });

    jQuery('.bxslider').bxSlider({
        auto: false,
        autoControls: false,
        mode: 'fade',
        useCSS: false,
        easing: 'easeInOut',
        speed: 4000,
        pause: 4000,
        autoHover: true,
        captions: false,
        adaptiveHeight: true
    });


    jQuery(".div_slider").css("width", larghezza + "px");

    padding = (altezza - 62) / 2;
    jQuery(".bx-pager").css("padding-top", padding + "px");
}


function adatta(height) {
    if (jQuery(window).width()>770){
        jQuery(".blocco5 #block3.desktop").css("display","block");
        jQuery(".blocco5 #block3.mobile").css("display","none");
    }
    else {
        jQuery(".blocco5 #block3.desktop").css("display","none");
        jQuery(".blocco5 #block3.mobile").css("display","block");
    }
//blocco designer
    altezzaDesigner = jQuery(".blocco1 #block1 .designers").height();
    altezzaBlocco2 = jQuery(".blocco1 #block2").height();
    margine = (altezzaBlocco2 - altezzaDesigner) / 2;
    jQuery(".blocco1 #block1 .designers").css("margin-top", margine + "px");

    //blocco donna
    larghezzaTot = jQuery(window).width();
    larghezzaTot = Math.floor(larghezzaTot / 5);
    jQuery(".blocco4 #block1").css("height", larghezzaTot);
    jQuery(".blocco4 #block2").css("width", larghezzaTot);
    jQuery(".blocco4 #block3").css("width", larghezzaTot);
    jQuery(".blocco4 #block4").css("width", larghezzaTot);

    jQuery(".blocco4 figure").css("width", larghezzaTot);
    altezzaTesto = jQuery(".blocco4 #block1 .testo").height();
    margine = (larghezzaTot - (altezzaTesto + 20)) / 2;
    jQuery(".blocco4 #block1 .testo").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco4 #block1 .testo").width();
    lunghezzaB = jQuery(".blocco4 #block1").width();
    margine = (lunghezzaB - (lunghezzaTesto + 20)) / 2;
    jQuery(".blocco4 #block1 .testo").css("margin-left", margine + "px");

    alt1 = jQuery(".blocco4 figure figcaption").height();
    alt2 = jQuery(".blocco4 figure figcaption p").height();
    margine = (alt1 - alt2) / 2;
    jQuery(".blocco4 figure figcaption p").css("margin-top", margine + "px");

    //blocco uomo
    larghezzaTot = jQuery(window).width();
    larghezzaTot = Math.floor(larghezzaTot / 5);
    jQuery(".blocco5 #block3").css("height", larghezzaTot);
    jQuery(".blocco5 #block1").css("width", larghezzaTot);
    jQuery(".blocco5 #block2").css("width", larghezzaTot);
    jQuery(".blocco5 #block4").css("width", larghezzaTot);
    jQuery(".blocco5 figure").css("width", larghezzaTot);

    alt1 = jQuery(".blocco5 figure figcaption").height();
    alt2 = jQuery(".blocco5 figure figcaption p").height();
    margine = (alt1 - alt2) / 2;
    jQuery(".blocco5 figure figcaption p").css("margin-top", margine + "px");

    altezzaTesto = jQuery(".blocco5 #block3.desktop .testo").height();
    margine = (larghezzaTot - (altezzaTesto + 20)) / 2;
    jQuery(".blocco5 #block3.desktop .testo").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco5 #block3.desktop .testo").width();
    lunghezzaB = jQuery(".blocco5 #block3.desktop").width();
    margine = (lunghezzaB - (lunghezzaTesto + 20)) / 2;
    jQuery(".blocco5 #block3.desktop .testo").css("margin-left", margine + "px");

    //blocco boutique
    altezzaC = jQuery("#img_coltorti").height();
    jQuery(".blocco2 #block1").css("height", altezzaC);
    jQuery(".blocco2 #block3").css("height", altezzaC);
    altezzaTesto = jQuery(".blocco2 #block1 .boutique").height();
    margine = (altezzaC - (altezzaTesto + 22)) / 2;
    jQuery(".blocco2 #block1 .boutique").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco2 #block1 .boutique").width();
    lunghezzaB = jQuery(".blocco2 #block1").width();
    margine = (lunghezzaB - (lunghezzaTesto + 22)) / 2;
    jQuery(".blocco2 #block1 .boutique").css("margin-left", margine + "px");
    altezzaImg = altezzaC - 200;
    jQuery(".blocco2 #block3 .product_home img").css("height", altezzaImg + "px");
    altezzaProduct = jQuery(".blocco2 #block3 .product_home").height();
    margine = (altezzaC - altezzaProduct) / 2;
    jQuery(".blocco2 #block3 .product_home h5").css("margin-bottom", margine + "px");


    //blocco filosofia
    altezzaB = jQuery("#img_boutique").height();
    jQuery(".blocco3 #block1").css("height", altezzaB);
    jQuery(".blocco3 #block2").css("height", altezzaB);
    altezzaTesto = jQuery(".blocco3 #block2 .coltorti").height();
    margine = (altezzaB - (altezzaTesto + 20)) / 2;
    jQuery(".blocco3 #block2 .coltorti").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco3 #block2 .coltorti .sottotitolo").width();
    lunghezzaB = jQuery(".blocco3 #block2").width();
    margine = (lunghezzaB - (lunghezzaTesto + 20)) / 2;
    jQuery(".blocco3 #block2 .coltorti").css("margin-left", margine + "px");
    altezzaTesto = jQuery(".blocco3 #block1 .filosofia").height();
    margine = (altezzaC - (altezzaTesto + 20)) / 2;
    jQuery(".blocco3 #block1 .filosofia").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco3 #block1 .filosofia").width();
    lunghezzaB = jQuery(".blocco3 #block1").width();
    margine = (lunghezzaB - (lunghezzaTesto + 20)) / 2;
    jQuery(".blocco3 #block1 .filosofia").css("margin-left", margine + "px");


    //blocco yps
    altezzaC = jQuery("#img_yps_donna").height();
    jQuery(".blocco8 #block1").css("height", altezzaC);
    jQuery(".blocco8 #block2 .block_uomo").css("height", altezzaC);
    jQuery(".blocco8 #block3 .block_donna").css("height", altezzaC);
    altezzaTesto = jQuery(".blocco8 #block1 .yps").height();
    margine = (altezzaC - (altezzaTesto + 20)) / 2;
    jQuery(".blocco8 #block1 .yps").css("margin-top", margine + "px");
    lunghezzaTesto = jQuery(".blocco8 #block1 .yps").width();
    lunghezzaB = jQuery(".blocco8 #block1").width();
    margine = (lunghezzaB - (lunghezzaTesto + 20)) / 2;
    jQuery(".blocco8 #block1 .yps").css("margin-left", margine + "px");

    jQuery(".blocco8 #block2 .block_uomo").css("display", "block");
    jQuery(".blocco8 #block3 .block_donna").css("display", "block");
    alte1 = jQuery(".blocco8 #block2 .block_uomo .stile").height();
    alte2 = jQuery(".blocco8 #block2 .block_uomo .occasione ").height();
    alte3 = jQuery(".blocco8 #block2 .block_uomo .bottone ").height();
    altezza = (altezzaC - (alte2 + alte1 + alte3 + 20 + 50)) / 2;
    jQuery(".blocco8 #block2 .block_uomo .stile").css("margin-top", altezza + "px");
    width1 = jQuery(".blocco8 #block2 .block_uomo .stile .valori .big").width();
    width2 = jQuery(".blocco8 #block2 .block_uomo .occasione .valori .big").width();
    jQuery(".blocco8 #block2 .block_uomo .stile .valori .stile_valore").css("width", (width1 + 32) + "px");
    jQuery(".blocco8 #block2 .block_uomo .occasione .valori .stile_valore").css("width", (width2 + 32) + "px");
    larghezza = jQuery(".blocco8 #block2 .block_uomo").width();
    padding = (larghezza - (((width1 + 32) * 3) + 20)) / 2;
    jQuery(".blocco8 #block2 .block_uomo .stile .valori").css("padding-left", padding + "px");
    padding2 = (larghezza - (((width2 + 32) * 3) + 20)) / 2;
    jQuery(".blocco8 #block2 .block_uomo .occasione .valori").css("padding-left", padding2 + "px");

    alte1 = jQuery(".blocco8 #block3 .block_donna .stile").height();
    alte2 = jQuery(".blocco8 #block3 .block_donna .occasione ").height();
    alte3 = jQuery(".blocco8 #block3 .block_donna .bottone ").height();
    altezza = (altezzaC - (alte2 + alte1 + alte3 + 20 + 50)) / 2;
    jQuery(".blocco8 #block3 .block_donna .stile").css("margin-top", altezza + "px");
    width1 = jQuery(".blocco8 #block3 .block_donna .stile .valori .big").width();
    width2 = jQuery(".blocco8 #block3 .block_donna .occasione .valori .big").width();
    jQuery(".blocco8 #block3 .block_donna .stile .valori .stile_valore").css("width", (width1 + 32) + "px");
    jQuery(".blocco8 #block3 .block_donna .occasione .valori .stile_valore").css("width", (width2 + 32) + "px");
    larghezza = jQuery(".blocco8 #block3 .block_donna").width();
    padding = (larghezza - (((width1 + 32) * 3) + 20)) / 2;
    jQuery(".blocco8 #block3 .block_donna .stile .valori").css("padding-left", padding + "px");
    padding2 = (larghezza - (((width2 + 32) * 3) + 20)) / 2;
    jQuery(".blocco8 #block3 .block_donna .occasione .valori").css("padding-left", padding2 + "px");

    alt1 = jQuery(".blocco8 figure figcaption").height();
    alt2 = jQuery(".blocco8 figure figcaption .crea_stile").height();
    margine = (alt1 - alt2) / 2;
    jQuery(".blocco8 figure figcaption .crea_stile").css("margin-top", margine + "px");

    jQuery(".blocco8 #block2 .block_uomo").css("display", "none");
    jQuery(".blocco8 #block3 .block_donna").css("display", "none");
}



</script>
<?php /*
<div id="container" class="cont_video" style="position: relative;overflow: hidden;margin:0 auto;top:100px">
    <video poster="<?php echo $this->getSkinUrl("images/poster.jpg") ?>"  id="video_home2" style="top:0;z-index:2;height: auto" autobuffer  class="video_home" class="video-js vjs-default-skin" preload="auto">
        <source src="<?php echo $this->getSkinUrl("video/intro_coltorti.mp4") ?>" type="video/mp4" />
    </video>
</div>
<!--<video poster="<?php //echo $this->getSkinUrl("images/poster.jpg") ?>" id="video_home" autobuffer  class="video_home" class="video-js vjs-default-skin" preload="auto">
    <source src="http://www.coltortiboutique.com/intro_coltorti.mp4" type="video/mp4" />
</video>-->
<!--<div class="skip_intro">
    <button class="button" title="Skip" type="button"><span><span>SKIP -></span></span></button>
</div>-->
<div class="skip_intro">
    <button type="button" class="button_secondary" style="margin-bottom:20px">Skip -></button>
</div>
*/
?>