<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Prenota Reso') ?></h1>
</div>
<form id="resi_form" name="resi_form" action="<?php echo $this->getUrl('trec-resi/') ?>index/sendemail" method="post">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <div class="input-box">
                        <input name="id_ordine" id="id_ordine" placeholder="<?php echo $this->__("ID Ordine") ?> *" title="<?php echo $this->__('ID Ordine') ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <div class="input-box">
                        <input name="nome" id="nome" title="Name" placeholder="<?php echo $this->__("Nome") ?> *" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <div class="input-box">
                        <input name="cognome" id="cognome" placeholder="<?php echo $this->__("Cognome") ?> *" title="Surname" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <div class="input-box">
                        <input name="email" id="email" placeholder="<?php echo $this->__("Email") ?> *" title="Email" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button style="float:none" type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button button_secondary"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>



</form>
<script type="text/javascript">
    //<![CDATA[
    var resiForm = new VarienForm('resi_form', true);
    //]]>
</script>
