<script>

    jQuery(window).load(function () {
        adatta();
        jQuery(window).resize(function () {
            adatta();
        });
    });

    function adatta() {
        // blocco iniziale
        altezzaWindows=jQuery(window).height();
        altezzaBlocco=altezzaWindows-125;
        jQuery(".titolo_scopri").css("height", altezzaBlocco+"px");


    }
</script>
<div class="titolo_scopri" style="background-image:url(<?php echo $this->getSkinUrl('images/brands/alexander-wang/alexander-wang-coltorti-ancona.jpg') ?>);background-size:100%;background-repeat:no-repeat;">
    <div class="contenuto">
        <h1>Alexander Wang</h1>
        <p class="sottotitolo">Coltorti / <span>Designer</span></p>
        <button type="button" name="shop" id="shop" class="shop">vai allo shop</button>
        <p class="italic">Brand disponibile anche in boutiques</p>
    </div>
</div>

<div class="contenuto_scopri">
    <div class="blocco1 visibile">
        <div class="immagine">
            &nbsp;
        </div>
        <div class="testo">
            <h1>Alexander Wang</h1>
            <p class="sottotitolo">SS 2015 collection</p>
            <p class="titolo">Alexander Wang conquista con una collezione sexy dalle linee geometriche e dettagli futuristici.<br>I colori predominanti sono il bianco e il nero contrastati dal bluette, dal giallo e dall’arancione.</p>
        </div>
    </div>
    <div class="blocco2 visibile">
        <div class="testo">
            <div class="cont_testo">
                <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            </div>
        </div>
        <div class="immagine">
            &nbsp;
        </div>
    </div>
    <div class="blocco3 visibile">
        <div class="immagine">
            &nbsp;
        </div>
        <div class="testo">
            <div class="cont_testo">
                <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            </div>
        </div>
    </div>
    <div class="blocco4 visibile">
        <div class="testo">
            <div class="cont_testo">
                <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
        <div class="immagine">
            &nbsp;
        </div>
    </div>
    <div class="blocco6 visibile">
        <div class="testo">
            <button type="button" name="shop" id="shop" class="shop">vai allo shop alexander wang</button>
            <p class="italic">Brand disponibile anche in boutiques</p>
        </div>
    </div>
    <div class="blocco7 visibile">
        <div class="testo">
            <div style="height:250px">&nbsp;</div>
            <p>ALEXANDER WANG.COM</p>
        </div>
    </div>
</div>




