<?php
$unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
    'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
    'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
    'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
    'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y' );


$url="https://catalog.coltortiboutique.com/en";



?>

<div class="titolo_designer">
    <img alt="Brand" title="Brand" src="<?php echo $this->getSkinUrl("images/coltorti_brands_bg.jpg") ?>" class="img_designer_mobile" />
    <div class="contenuto">
        <h1>Brands</h1>
        <p class="sottotitolo"><?php echo $this->__("Selezione dei migliori brands") ?></p>
        <button type="button" name="seleziona" id="seleziona" class="button_secondary"><?php echo $this->__("seleziona") ?></button>
    </div>
</div>
<p class="scroll_down" style="opacity: 1;float: left;width: 100%;margin-top:-63px;text-align: center"></p>
<?php
if (Mage::app()->getStore()->getStoreId()=="1") {
    $link="scopri";
}
else if (Mage::app()->getStore()->getStoreId()=="2" || Mage::app()->getStore()->getStoreId()=="3") {
    $link="discover";
}
$k=0;
$brands=$this->getBrands2();
$categoria="";
foreach ($brands as $brand){
    $nome = $brand["nome"];
    $id = $brand["id"];
    $prodotti = $brand["prodotti"];
    $categoria = $brand["categoria"];

    if (strtolower($nome) == "adidas raf simons" ||
        strtolower($nome) == "alexander mcqueen" ||
        strtolower($nome) == "alexander wang" ||
        strtolower($nome) == "balenciaga" ||
        strtolower($nome) == "bally" ||
        strtolower($nome) == "barba" ||
        strtolower($nome) == "bottega veneta" ||
        strtolower($nome) == "burberry" ||
        strtolower($nome) == "céline" ||
        strtolower($nome) == "charlotte olympia" ||
        strtolower($nome) == "chiara ferragni" ||
        strtolower($nome) == "chloe'" ||
        strtolower($nome) == "christian dior" ||
        strtolower($nome) == "christopher kane" ||
        strtolower($nome) == "dolce & gabbana" ||
        strtolower($nome) == "dsquared2" ||
        strtolower($nome) == "ermanno scervino" ||
        strtolower($nome) == "faliero sarti" ||
        strtolower($nome) == "fausto puglisi" ||
        strtolower($nome) == "fendi" ||
        strtolower($nome) == "gianluca capannolo" ||
        strtolower($nome) == "gianvito rossi" ||
        strtolower($nome) == "giorgio armani" ||
        strtolower($nome) == "giorgio brato" ||
        strtolower($nome) == "giuseppe zanotti" ||
        strtolower($nome) == "golden goose" ||
        strtolower($nome) == "haider ackermann" ||
        strtolower($nome) == "isabel marant" ||
        strtolower($nome) == "jil sander" ||
        strtolower($nome) == "jimmy choo" ||
        strtolower($nome) == "kenzo" ||
        strtolower($nome) == "lanvin" ||
        strtolower($nome) == "loewe" ||
        strtolower($nome) == "maison margiela" ||
        strtolower($nome) == "marcelo burlon" ||
        strtolower($nome) == "marco bologna" ||
        strtolower($nome) == "michael kors" ||
        strtolower($nome) == "missoni" ||
        strtolower($nome) == "miu miu" ||
        strtolower($nome) == "moncler" ||
        strtolower($nome) == "moncler gamme rouge/bleu" ||
        strtolower($nome) == "mr&mrs italy" ||
        strtolower($nome) == "msgm" ||
        strtolower($nome) == "mulberry" ||
        strtolower($nome) == "paula cademartori" ||
        strtolower($nome) == "peter pilotto" ||
        strtolower($nome) == "pierre louis mascia" ||
        strtolower($nome) == "pollini" ||
        strtolower($nome) == "prada" ||
        strtolower($nome) == "proenza schouler" ||
        strtolower($nome) == "rick owens" ||
        strtolower($nome) == "roger vivier" ||
        strtolower($nome) == "sacai" ||
        strtolower($nome) == "saint laurent" ||
        strtolower($nome) == "salvatore ferragamo" ||
        strtolower($nome) == "stella mccartney" ||
        strtolower($nome) == "stuart weitzman" ||
        strtolower($nome) == "sveva" ||
        strtolower($nome) == "tagliatore" ||
        strtolower($nome) == "tom ford" ||
        strtolower($nome) == "tonello" ||
        strtolower($nome) == "valentino" ||
        strtolower($nome) == "versace"
    ) {


        $nome = html_entity_decode($nome, ENT_QUOTES, 'utf-8');
        $url_key = url_slug($nome);
        $url_key = strtr($url_key, $unwanted_array);
        $url_immagine = "images/brands/" . $url_key . ".jpg";
        if ($k & 1) {
            $riga = "0"; // numero dispari
        } else {
            $riga = "1"; //numero pari
        }

        if ($riga == 1) {
            echo '<span class="anchor"  id="'.$url_key.'"></span>';
            echo "<div class='div_designer visibile div_designer_dispari'";
            if (strtolower($nome) == "versace"){
                echo " id=\"last\"";
            }
            echo ">";
            echo "<div class='div_esterno'><div class='contenuto'>";
            echo "<h1>" . $nome . "</h1>";

            echo "<p>".$this->__($categoria)."</p>";

            if (strtolower($nome) == "adidas raf simons" ||
                strtolower($nome) == "alexander mcqueen" ||
                strtolower($nome) == "alexander wang" ||
                strtolower($nome) == "balenciaga" ||
                strtolower($nome) == "bally" ||
                strtolower($nome) == "balmain" ||
                strtolower($nome) == "bottega veneta" ||
                strtolower($nome) == "burberry" ||
                strtolower($nome) == "céline" ||
                strtolower($nome) == "charlotte olympia" ||
                strtolower($nome) == "chiara ferragni" ||
                strtolower($nome) == "chloe'" ||
                strtolower($nome) == "christian dior" ||
                strtolower($nome) == "christopher kane" ||
                strtolower($nome) == "dolce & gabbana" ||
                strtolower($nome) == "dsquared2" ||
                strtolower($nome) == "ermanno scervino" ||
                strtolower($nome) == "dsquared2" ||
                strtolower($nome) == "faliero sarti" ||
                strtolower($nome) == "fausto puglisi" ||
                strtolower($nome) == "fendi" ||
                strtolower($nome) == "gianluca capannolo" ||
                strtolower($nome) == "gianvito rossi" ||
                strtolower($nome) == "giorgio armani" ||
                strtolower($nome) == "giuseppe zanotti" ||
                strtolower($nome) == "golden goose" ||
                strtolower($nome) == "haider ackermann" ||
                strtolower($nome) == "isabel marant" ||
                strtolower($nome) == "jil sander" ||
                strtolower($nome) == "jimmy choo" ||
                strtolower($nome) == "kenzo" ||
                strtolower($nome) == "lanvin" ||
                strtolower($nome) == "loewe" ||
                strtolower($nome) == "maison margiela" ||
                strtolower($nome) == "marcelo burlon" ||
                strtolower($nome) == "marco bologna" ||
                strtolower($nome) == "michael kors" ||
                strtolower($nome) == "missoni" ||
                strtolower($nome) == "miu miu" ||
                strtolower($nome) == "moncler" ||
                strtolower($nome) == "moncler gamme rouge/bleu" ||
                strtolower($nome) == "msgm" ||
                strtolower($nome) == "mulberry" ||
                strtolower($nome) == "paula cademartori" ||
                strtolower($nome) == "peter pilotto" ||
                strtolower($nome) == "pollini" ||
                strtolower($nome) == "prada" ||
                strtolower($nome) == "proenza schouler" ||
                strtolower($nome) == "rick owens" ||
                strtolower($nome) == "roger vivier" ||
                strtolower($nome) == "sacai" ||
                strtolower($nome) == "saint laurent" ||
                strtolower($nome) == "salvatore ferragamo" ||
                strtolower($nome) == "stella mccartney" ||
                strtolower($nome) == "stuart weitzman" ||
                strtolower($nome) == "tom ford" ||
                strtolower($nome) == "tonello" ||
                strtolower($nome) == "valentino" ||
            strtolower($nome) == "versace"
            ) {

                echo "<div class='button_div'>";
                echo "<button type='button' name='discover' value='Discover' onclick=\"window.location='" . Mage::getBaseUrl() . $link."-" . $url_key . "'\">Discover brand</button>";
                if ($prodotti == 1) {
                    echo "<button type='button' name='shop' value='shop' class=\"shop_designer\" onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\">Shop Now</button>";
                }
                echo "</div>";
                echo "<div class='button_div_mobile'>";
                echo "<button type='button' name='discover' value='Discover' onclick=\"window.location='" . Mage::getBaseUrl() . $link."-" . $url_key . "'\">Discover brand</button>";
                if ($prodotti == 1) {
                    echo "<br><button type='button' name='shop' value='shop' class=\"shop_designer\" onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\" >Shop Now</button>";
                }
                echo "</div>";
            }
            else {
                if ($prodotti == 1) {
                    echo "<div class='button_div'>";
                    echo "<button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\" >Shop Now</button>";
                    echo "</div>";
                }
                if ($prodotti == 1) {
                    echo "<div class='button_div_mobile'>";
                    echo "<br><button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\" >Shop Now</button>";
                    echo "</div>";
                }
            }
            echo "</div></div>";
            echo "<div class='immagine'><img alt=\"".$this->__('New Collection %s',$nome)."\" title=\"".$this->__('New Collection %s',$nome)."\" src='" . $this->getSkinUrl($url_immagine) . "'  />";
            echo "</div></div>";
        } else {
            echo '<span class="anchor"  id="'.$url_key.'"></span>';
            echo "<div class='div_designer visibile div_designer_pari'";
            if (strtolower($nome) == "versace"){
                echo " id=\"last\"";
            }
            echo ">";

            echo "<div class='immagine'><img alt=\"".$this->__('New Collection %s',$nome)."\" title=\"".$this->__('New Collection %s',$nome)."\" src='" . $this->getSkinUrl($url_immagine) . "'  />";
            echo "</div>";
            echo "<div class='div_esterno'><div class='contenuto'>";
            echo "<h1>" . $nome . "</h1>";
            echo "<p>".$this->__($categoria)."</p>";
            if (strtolower($nome) == "adidas raf simons" ||
                strtolower($nome) == "alexander mcqueen" ||
                strtolower($nome) == "alexander wang" ||
                strtolower($nome) == "balenciaga" ||
                strtolower($nome) == "bally" ||
                strtolower($nome) == "balmain" ||
                strtolower($nome) == "bottega veneta" ||
                strtolower($nome) == "burberry" ||
                strtolower($nome) == "céline" ||
                strtolower($nome) == "charlotte olympia" ||
                strtolower($nome) == "chiara ferragni" ||
                strtolower($nome) == "chloe'" ||
                strtolower($nome) == "christian dior" ||
                strtolower($nome) == "christopher kane" ||
                strtolower($nome) == "dolce & gabbana" ||
                strtolower($nome) == "dsquared2" ||
                strtolower($nome) == "ermanno scervino" ||
                strtolower($nome) == "dsquared2" ||
                strtolower($nome) == "faliero sarti" ||
                strtolower($nome) == "fausto puglisi" ||
                strtolower($nome) == "fendi" ||
                strtolower($nome) == "gianluca capannolo" ||
                strtolower($nome) == "gianvito rossi" ||
                strtolower($nome) == "giorgio armani" ||
                strtolower($nome) == "giuseppe zanotti" ||
                strtolower($nome) == "golden goose" ||
                strtolower($nome) == "haider ackermann" ||
                strtolower($nome) == "isabel marant" ||
                strtolower($nome) == "jil sander" ||
                strtolower($nome) == "jimmy choo" ||
                strtolower($nome) == "kenzo" ||
                strtolower($nome) == "lanvin" ||
                strtolower($nome) == "loewe" ||
                strtolower($nome) == "maison margiela" ||
                strtolower($nome) == "marcelo burlon" ||
                strtolower($nome) == "marco bologna" ||
                strtolower($nome) == "michael kors" ||
                strtolower($nome) == "missoni" ||
                strtolower($nome) == "miu miu" ||
                strtolower($nome) == "moncler" ||
                strtolower($nome) == "moncler gamme rouge/bleu" ||
                strtolower($nome) == "msgm" ||
                strtolower($nome) == "mulberry" ||
                strtolower($nome) == "paula cademartori" ||
                strtolower($nome) == "peter pilotto" ||
                strtolower($nome) == "pollini" ||
                strtolower($nome) == "prada" ||
                strtolower($nome) == "proenza schouler" ||
                strtolower($nome) == "rick owens" ||
                strtolower($nome) == "roger vivier" ||
                strtolower($nome) == "sacai" ||
                strtolower($nome) == "saint laurent" ||
                strtolower($nome) == "salvatore ferragamo" ||
                strtolower($nome) == "stella mccartney" ||
                strtolower($nome) == "stuart weitzman" ||
                strtolower($nome) == "tom ford" ||
                strtolower($nome) == "tonello" ||
                strtolower($nome) == "valentino" ||
                strtolower($nome) == "versace"
            ) {
                echo "<div class='button_div'><button type='button' name='discover' value='Discover' onclick=\"window.location='" . Mage::getBaseUrl() . $link."-" . $url_key . "'\">Discover brand</button>";
                if ($prodotti == 1) {
                    echo "<button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\"  class=\"shop_designer\">Shop Now</button>";
                }
echo "</div>";
                echo "<div class='button_div_mobile'><button type='button' name='discover' value='Discover' onclick=\"window.location='" . Mage::getBaseUrl() . $link."-" . $url_key . "'\">Discover brand</button>";
                if ($prodotti == 1) {
                    echo "<br><button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\"  class=\"shop_designer\">Shop Now</button>";
                }
                echo "</div>";
            }
            else {
                if ($prodotti == 1) {
                    echo "<div class='button_div'>";
                    echo "<button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\" >Shop Now</button>";
                    echo "</div>";
                }
                if ($prodotti == 1) {
                    echo "<div class='button_div_mobile'>";
                    echo "<br><button type='button' name='shop' value='shop' onclick=\"window.location='" . Mage::getBaseUrl() . "" . $url_key . ".html'\" >Shop Now</button>";
                    echo "</div>";
                }
            }
            echo "</div></div>";
            echo "</div>";
        }

        $k = $k + 1;
    }

}


?>

<?php


function url_slug($str, $options = array()) {
    // Make sure string is in UTF-8 and strip invalid UTF-8 characters
    $str = mb_convert_encoding((string)$str, 'UTF-8', mb_list_encodings());

    $defaults = array(
        'delimiter' => '-',
        'limit' => null,
        'lowercase' => true,
        'replacements' => array(),
        'transliterate' => false,
    );

    // Merge options
    $options = array_merge($defaults, $options);

    $char_map = array(
        // Latin
        'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'AE', 'Ç' => 'C',
        'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I',
        'Ð' => 'D', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O', 'Ő' => 'O',
        'Ø' => 'O', 'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ű' => 'U', 'Ý' => 'Y', 'Þ' => 'TH',
        'ß' => 'ss',
        'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a', 'æ' => 'ae', 'ç' => 'c',
        'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e', 'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
        'ð' => 'd', 'ñ' => 'n', 'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ő' => 'o',
        'ø' => 'o', 'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u', 'ű' => 'u', 'ý' => 'y', 'þ' => 'th',
        'ÿ' => 'y',

        // Latin symbols
        '©' => '(c)',

        // Greek
        'Α' => 'A', 'Β' => 'B', 'Γ' => 'G', 'Δ' => 'D', 'Ε' => 'E', 'Ζ' => 'Z', 'Η' => 'H', 'Θ' => '8',
        'Ι' => 'I', 'Κ' => 'K', 'Λ' => 'L', 'Μ' => 'M', 'Ν' => 'N', 'Ξ' => '3', 'Ο' => 'O', 'Π' => 'P',
        'Ρ' => 'R', 'Σ' => 'S', 'Τ' => 'T', 'Υ' => 'Y', 'Φ' => 'F', 'Χ' => 'X', 'Ψ' => 'PS', 'Ω' => 'W',
        'Ά' => 'A', 'Έ' => 'E', 'Ί' => 'I', 'Ό' => 'O', 'Ύ' => 'Y', 'Ή' => 'H', 'Ώ' => 'W', 'Ϊ' => 'I',
        'Ϋ' => 'Y',
        'α' => 'a', 'β' => 'b', 'γ' => 'g', 'δ' => 'd', 'ε' => 'e', 'ζ' => 'z', 'η' => 'h', 'θ' => '8',
        'ι' => 'i', 'κ' => 'k', 'λ' => 'l', 'μ' => 'm', 'ν' => 'n', 'ξ' => '3', 'ο' => 'o', 'π' => 'p',
        'ρ' => 'r', 'σ' => 's', 'τ' => 't', 'υ' => 'y', 'φ' => 'f', 'χ' => 'x', 'ψ' => 'ps', 'ω' => 'w',
        'ά' => 'a', 'έ' => 'e', 'ί' => 'i', 'ό' => 'o', 'ύ' => 'y', 'ή' => 'h', 'ώ' => 'w', 'ς' => 's',
        'ϊ' => 'i', 'ΰ' => 'y', 'ϋ' => 'y', 'ΐ' => 'i',

        // Turkish
        'Ş' => 'S', 'İ' => 'I', 'Ç' => 'C', 'Ü' => 'U', 'Ö' => 'O', 'Ğ' => 'G',
        'ş' => 's', 'ı' => 'i', 'ç' => 'c', 'ü' => 'u', 'ö' => 'o', 'ğ' => 'g',

        // Russian
        'А' => 'A', 'Б' => 'B', 'В' => 'V', 'Г' => 'G', 'Д' => 'D', 'Е' => 'E', 'Ё' => 'Yo', 'Ж' => 'Zh',
        'З' => 'Z', 'И' => 'I', 'Й' => 'J', 'К' => 'K', 'Л' => 'L', 'М' => 'M', 'Н' => 'N', 'О' => 'O',
        'П' => 'P', 'Р' => 'R', 'С' => 'S', 'Т' => 'T', 'У' => 'U', 'Ф' => 'F', 'Х' => 'H', 'Ц' => 'C',
        'Ч' => 'Ch', 'Ш' => 'Sh', 'Щ' => 'Sh', 'Ъ' => '', 'Ы' => 'Y', 'Ь' => '', 'Э' => 'E', 'Ю' => 'Yu',
        'Я' => 'Ya',
        'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'yo', 'ж' => 'zh',
        'з' => 'z', 'и' => 'i', 'й' => 'j', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o',
        'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c',
        'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu',
        'я' => 'ya',

        // Ukrainian
        'Є' => 'Ye', 'І' => 'I', 'Ї' => 'Yi', 'Ґ' => 'G',
        'є' => 'ye', 'і' => 'i', 'ї' => 'yi', 'ґ' => 'g',

        // Czech
        'Č' => 'C', 'Ď' => 'D', 'Ě' => 'E', 'Ň' => 'N', 'Ř' => 'R', 'Š' => 'S', 'Ť' => 'T', 'Ů' => 'U',
        'Ž' => 'Z',
        'č' => 'c', 'ď' => 'd', 'ě' => 'e', 'ň' => 'n', 'ř' => 'r', 'š' => 's', 'ť' => 't', 'ů' => 'u',
        'ž' => 'z',

        // Polish
        'Ą' => 'A', 'Ć' => 'C', 'Ę' => 'e', 'Ł' => 'L', 'Ń' => 'N', 'Ó' => 'o', 'Ś' => 'S', 'Ź' => 'Z',
        'Ż' => 'Z',
        'ą' => 'a', 'ć' => 'c', 'ę' => 'e', 'ł' => 'l', 'ń' => 'n', 'ó' => 'o', 'ś' => 's', 'ź' => 'z',
        'ż' => 'z',

        // Latvian
        'Ā' => 'A', 'Č' => 'C', 'Ē' => 'E', 'Ģ' => 'G', 'Ī' => 'i', 'Ķ' => 'k', 'Ļ' => 'L', 'Ņ' => 'N',
        'Š' => 'S', 'Ū' => 'u', 'Ž' => 'Z',
        'ā' => 'a', 'č' => 'c', 'ē' => 'e', 'ģ' => 'g', 'ī' => 'i', 'ķ' => 'k', 'ļ' => 'l', 'ņ' => 'n',
        'š' => 's', 'ū' => 'u', 'ž' => 'z'
    );

    // Make custom replacements
    $str = preg_replace(array_keys($options['replacements']), $options['replacements'], $str);

    // Transliterate characters to ASCII
    if ($options['transliterate']) {
        $str = str_replace(array_keys($char_map), $char_map, $str);
    }

    // Replace non-alphanumeric characters with our delimiter
    $str = preg_replace('/[^\p{L}\p{Nd}]+/u', $options['delimiter'], $str);

    // Remove duplicate delimiters
    $str = preg_replace('/(' . preg_quote($options['delimiter'], '/') . '){2,}/', '$1', $str);

    // Truncate slug to max. characters
    $str = mb_substr($str, 0, ($options['limit'] ? $options['limit'] : mb_strlen($str, 'UTF-8')), 'UTF-8');

    // Remove delimiter from ends
    $str = trim($str, $options['delimiter']);

    return $options['lowercase'] ? mb_strtolower($str, 'UTF-8') : $str;
}
?>