<?php
$unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
    'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
    'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
    'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
    'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y' );


$productModel = Mage::getModel('catalog/product');

    $str_attr_label="ca_brand";
    $int_attr_value=$this->getData("brand_id");
    $attr = $productModel->getResource()->getAttribute($str_attr_label);


        $nome = $attr->getSource()->getOptionText($int_attr_value);
        $url_key = url_slug($nome);

        $url_key = strtr($url_key, $unwanted_array);

        $result=$this->getTitleBrand($int_attr_value);

        foreach ($result as $row){
            $testo_first = $row["testo"];
            $testo_first=str_replace(".",".<br>",$testo_first);
            $categoria=$row["categoria"];
        }




$arrayProdotti=$this->getProductsBrand($int_attr_value);
?>
<div class="titolo_scopri" style="background-image:url(<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona.jpg') ?>);background-size:100%;background-repeat:no-repeat;">
    <div class="contenuto">
        <h1><?php echo $nome ?></h1>
        <p class="sottotitolo"><?php echo $this->__($categoria)  ?></p>
        <?php if (count($arrayProdotti)>0) { ?>
        <button type="button" name="shop" id="shop" class="button_secondary" onclick="<?php echo "window.location='".Mage::getUrl()."".$url_key.".html'" ?>"><?php echo $this->__("vai allo shop") ?></button>
        <?php } ?>
        <p class="italic"><?php echo $this->__("Brand disponibile nelle boutiques di") ?></p>
        <ul>
            <?php

            $result=$this->getBoutiquesBrand($int_attr_value);
            foreach ($result as $row){
                $boutiques=$row["boutiques"];
                $boutiques_url=url_slug($boutiques);
                echo "<li><a href='".Mage::getBaseUrl() ."boutique-".strtolower($boutiques_url)."'>".$boutiques."</a></li>";
            }
            ?>
        </ul>
    </div>
</div>
<p class="scroll_down" style="opacity: 1;float: left;width: 100%;margin:0;margin-top:-42px;text-align: center"></p>
<div class="contenuto_scopri">
    <div class="blocco1 visibile">
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-sfilata-coltorti-ancona.jpg') ?>" />
        </div>
        <div class="testo">
            <h1><?php echo $nome ?></h1>
            <p class="sottotitolo">FW 2015 collection</p>
            <p class="titolo"><?php echo $testo_first ?></p>
        </div>
    </div>
    <div class="blocco2 visibile">
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-sx.jpg') ?>" />
        </div>
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-dx.jpg') ?>" />
        </div>
    </div>
    <div class="blocco5 visibile">
        <div class="products">
            <?php
            echo '<ul class="lista_prodotti_hover">';
            for ($j=0; $j<count($arrayProdotti); $j++){

                $id_prodotto = $arrayProdotti[$j];
                $_product = Mage::getModel('catalog/product');

                $_product->load($id_prodotto);

                $stockItem = $_product->getStockItem();
                if($stockItem->getIsInStock()) {
                    $flag=false;
                    $img=$_product->load ( 'media_gallery' )->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                    if ($img!=null){
                        $over=$img->getFile();
                        $flag=true;
                    }
                    else {
                        $img = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position_default', '2');
                        if ($img != null) {
                            $over = $img->getFile();
                            $flag = true;
                        }
                    }

                    $_category = $this->getLastCategory($_product);
                    ?>
                    <li class="item last">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                <?php
                                if ($flag == true) {
                                    echo "onmouseover=\"this.src='" . $this->helper('catalog/image')->init($_product, 'small_image', $over) . "'\"";
                                    echo "onmouseout=\"this.src='" . $this->helper('catalog/image')->init($_product, 'small_image') . "'\"";
                                }
                                ?>
                                />
                        </a>

                        <div class="product-info">
                            <h2 class="product-name brand"><?php echo $_product->getAttributeText("ca_brand") ?></h2>

                            <h2 class="product-name name"><?php echo $_category->getName(); ?></h2>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </li>
                <?php
                }
            }

            echo "</ul>";
            ?>
        </div>
    </div>
    <div class="blocco3 visibile">
        <?php if (
            $int_attr_value==1069 ||
            $int_attr_value==1024 ||
            $int_attr_value==948 ||
            $int_attr_value==962 ||
            $int_attr_value==1008 ||
            $int_attr_value==985 ||
            $int_attr_value==993 ||
            $int_attr_value==939 ||
            $int_attr_value==955 ||
            $int_attr_value==1030 ||
            $int_attr_value==958) { ?>
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-sx2.jpg') ?>" />
        </div>
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-dx2.jpg') ?>" />
        </div>
        <?php } ?>
        <?php if (
            $int_attr_value==939 ||
            $int_attr_value==1030 ) { ?>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-sx3.jpg') ?>" />
            </div>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-dx3.jpg') ?>" />
            </div>
        <?php } ?>
        <?php if (
            $int_attr_value==939 ||
            $int_attr_value==1030 ) { ?>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-sx4.jpg') ?>" />
            </div>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-dx4.jpg') ?>" />
            </div>
        <?php } ?>
        <?php if (
            $int_attr_value==1030 ) { ?>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-sx5.jpg') ?>" />
            </div>
            <div class="immagine">
                <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-dx5.jpg') ?>" />
            </div>
        <?php } ?>

    </div>
    <div class="blocco4 visibile">
        <div class="immagine">
            <img alt="<?php echo $this->__('%s Collection',$nome) ?>" title="<?php echo $this->__('%s Collection',$nome) ?>" src="<?php echo $this->getSkinUrl('images/brands/'.$url_key.'/'.$url_key.'-coltorti-ancona-bottom.jpg') ?>" />
        </div>
    </div>
    <div class="blocco6 visibile">
        <div class="testo">
            <?php if (count($arrayProdotti)>0) { ?>
                <?php if (Mage::app()->getStore()->getStoreId()=="1") { ?>
            <button type="button" name="shop" id="shop" class="button_secondary" onclick="<?php echo "window.location='".Mage::getUrl()."".$url_key.".html'" ?>"><?php echo $this->__("vai allo shop") ?> <?php echo $nome ?></button>
            <?php } else if (Mage::app()->getStore()->getStoreId()=="2" || Mage::app()->getStore()->getStoreId()=="3") { ?>
                        <button type="button" name="shop" id="shop" class="button_secondary" onclick="<?php echo "window.location='".Mage::getUrl()."".$url_key.".html'" ?>"><?php echo "go to ".$nome." shop" ?></button>
            <?php }
                } ?>
            <p class="italic"><?php echo $this->__("Brand disponibile nelle boutiques di") ?></p>
            <ul id="lista_bou">
                <?php
                $result=$this->getBoutiquesBrand($int_attr_value);
                $l=0;
                foreach ($result as $row){
                    $boutiques=$row["boutiques"];
                    $boutiques_url=url_slug($boutiques);
                    $l=$l+1;
                    if ($l==count($result)){
                        echo "<li class='last'><a href='".Mage::getBaseUrl() ."boutique-".strtolower($boutiques_url)."'>".$boutiques."</a></li>";
                    }
                    else {
                        echo "<li><a href='".Mage::getBaseUrl() ."boutique-".strtolower($boutiques_url)."'>".$boutiques."</a></li>";
                    }
                }
                ?>
            </ul>
        </div>
    </div>
</div>
<?php
function url_slug($str, $options = array()) {
    // Make sure string is in UTF-8 and strip invalid UTF-8 characters
    $str = mb_convert_encoding((string)$str, 'UTF-8', mb_list_encodings());

    $defaults = array(
        'delimiter' => '-',
        'limit' => null,
        'lowercase' => true,
        'replacements' => array(),
        'transliterate' => false,
    );

    // Merge options
    $options = array_merge($defaults, $options);

    $char_map = array(
        // Latin
        'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'AE', 'Ç' => 'C',
        'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I',
        'Ð' => 'D', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O', 'Ő' => 'O',
        'Ø' => 'O', 'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ű' => 'U', 'Ý' => 'Y', 'Þ' => 'TH',
        'ß' => 'ss',
        'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a', 'æ' => 'ae', 'ç' => 'c',
        'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e', 'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
        'ð' => 'd', 'ñ' => 'n', 'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ő' => 'o',
        'ø' => 'o', 'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u', 'ű' => 'u', 'ý' => 'y', 'þ' => 'th',
        'ÿ' => 'y',

        // Latin symbols
        '©' => '(c)',

        // Greek
        'Α' => 'A', 'Β' => 'B', 'Γ' => 'G', 'Δ' => 'D', 'Ε' => 'E', 'Ζ' => 'Z', 'Η' => 'H', 'Θ' => '8',
        'Ι' => 'I', 'Κ' => 'K', 'Λ' => 'L', 'Μ' => 'M', 'Ν' => 'N', 'Ξ' => '3', 'Ο' => 'O', 'Π' => 'P',
        'Ρ' => 'R', 'Σ' => 'S', 'Τ' => 'T', 'Υ' => 'Y', 'Φ' => 'F', 'Χ' => 'X', 'Ψ' => 'PS', 'Ω' => 'W',
        'Ά' => 'A', 'Έ' => 'E', 'Ί' => 'I', 'Ό' => 'O', 'Ύ' => 'Y', 'Ή' => 'H', 'Ώ' => 'W', 'Ϊ' => 'I',
        'Ϋ' => 'Y',
        'α' => 'a', 'β' => 'b', 'γ' => 'g', 'δ' => 'd', 'ε' => 'e', 'ζ' => 'z', 'η' => 'h', 'θ' => '8',
        'ι' => 'i', 'κ' => 'k', 'λ' => 'l', 'μ' => 'm', 'ν' => 'n', 'ξ' => '3', 'ο' => 'o', 'π' => 'p',
        'ρ' => 'r', 'σ' => 's', 'τ' => 't', 'υ' => 'y', 'φ' => 'f', 'χ' => 'x', 'ψ' => 'ps', 'ω' => 'w',
        'ά' => 'a', 'έ' => 'e', 'ί' => 'i', 'ό' => 'o', 'ύ' => 'y', 'ή' => 'h', 'ώ' => 'w', 'ς' => 's',
        'ϊ' => 'i', 'ΰ' => 'y', 'ϋ' => 'y', 'ΐ' => 'i',

        // Turkish
        'Ş' => 'S', 'İ' => 'I', 'Ç' => 'C', 'Ü' => 'U', 'Ö' => 'O', 'Ğ' => 'G',
        'ş' => 's', 'ı' => 'i', 'ç' => 'c', 'ü' => 'u', 'ö' => 'o', 'ğ' => 'g',

        // Russian
        'А' => 'A', 'Б' => 'B', 'В' => 'V', 'Г' => 'G', 'Д' => 'D', 'Е' => 'E', 'Ё' => 'Yo', 'Ж' => 'Zh',
        'З' => 'Z', 'И' => 'I', 'Й' => 'J', 'К' => 'K', 'Л' => 'L', 'М' => 'M', 'Н' => 'N', 'О' => 'O',
        'П' => 'P', 'Р' => 'R', 'С' => 'S', 'Т' => 'T', 'У' => 'U', 'Ф' => 'F', 'Х' => 'H', 'Ц' => 'C',
        'Ч' => 'Ch', 'Ш' => 'Sh', 'Щ' => 'Sh', 'Ъ' => '', 'Ы' => 'Y', 'Ь' => '', 'Э' => 'E', 'Ю' => 'Yu',
        'Я' => 'Ya',
        'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'yo', 'ж' => 'zh',
        'з' => 'z', 'и' => 'i', 'й' => 'j', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o',
        'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c',
        'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu',
        'я' => 'ya',

        // Ukrainian
        'Є' => 'Ye', 'І' => 'I', 'Ї' => 'Yi', 'Ґ' => 'G',
        'є' => 'ye', 'і' => 'i', 'ї' => 'yi', 'ґ' => 'g',

        // Czech
        'Č' => 'C', 'Ď' => 'D', 'Ě' => 'E', 'Ň' => 'N', 'Ř' => 'R', 'Š' => 'S', 'Ť' => 'T', 'Ů' => 'U',
        'Ž' => 'Z',
        'č' => 'c', 'ď' => 'd', 'ě' => 'e', 'ň' => 'n', 'ř' => 'r', 'š' => 's', 'ť' => 't', 'ů' => 'u',
        'ž' => 'z',

        // Polish
        'Ą' => 'A', 'Ć' => 'C', 'Ę' => 'e', 'Ł' => 'L', 'Ń' => 'N', 'Ó' => 'o', 'Ś' => 'S', 'Ź' => 'Z',
        'Ż' => 'Z',
        'ą' => 'a', 'ć' => 'c', 'ę' => 'e', 'ł' => 'l', 'ń' => 'n', 'ó' => 'o', 'ś' => 's', 'ź' => 'z',
        'ż' => 'z',

        // Latvian
        'Ā' => 'A', 'Č' => 'C', 'Ē' => 'E', 'Ģ' => 'G', 'Ī' => 'i', 'Ķ' => 'k', 'Ļ' => 'L', 'Ņ' => 'N',
        'Š' => 'S', 'Ū' => 'u', 'Ž' => 'Z',
        'ā' => 'a', 'č' => 'c', 'ē' => 'e', 'ģ' => 'g', 'ī' => 'i', 'ķ' => 'k', 'ļ' => 'l', 'ņ' => 'n',
        'š' => 's', 'ū' => 'u', 'ž' => 'z'
    );

    // Make custom replacements
    $str = preg_replace(array_keys($options['replacements']), $options['replacements'], $str);

    // Transliterate characters to ASCII
    if ($options['transliterate']) {
        $str = str_replace(array_keys($char_map), $char_map, $str);
    }

    // Replace non-alphanumeric characters with our delimiter
    $str = preg_replace('/[^\p{L}\p{Nd}]+/u', $options['delimiter'], $str);

    // Remove duplicate delimiters
    $str = preg_replace('/(' . preg_quote($options['delimiter'], '/') . '){2,}/', '$1', $str);

    // Truncate slug to max. characters
    $str = mb_substr($str, 0, ($options['limit'] ? $options['limit'] : mb_strlen($str, 'UTF-8')), 'UTF-8');

    // Remove delimiter from ends
    $str = trim($str, $options['delimiter']);

    return $options['lowercase'] ? mb_strtolower($str, 'UTF-8') : $str;
}
?>


