<?php

$stores = Mage::app()->getStores();

foreach ($stores as $store)
{

    if ($store->getId()=="1"){
        $url=$store->getBaseUrl() . $this->getData('link_it');
        $storeCode = substr(Mage::getStoreConfig('general/locale/code', $store->getId()),0,2);
    }
    else if ($store->getId()=="2"){
        $url=$store->getBaseUrl() . $this->getData('link_en');
        $storeCode = substr(Mage::getStoreConfig('general/locale/code', $store->getId()),0,2);
    }
    else if ($store->getId()=="3"){
        $url=$store->getBaseUrl() . $this->getData('link_en_us');
        $storeCode = "en_us";
    }

    echo "<link rel=\"alternate\" hreflang=\"".$storeCode."\" href=\"".$url."\" />";

}
