<div class="titolo_scopri" style="background-image:url(<?php echo $this->getSkinUrl('images/brands/burberry/burberry-coltorti-ancona.jpg') ?>);background-size:100%;background-repeat:no-repeat;">
    <div class="contenuto">
        <h1>Burberry</h1>
        <p class="sottotitolo">Coltorti / <span>Designer</span></p>
        <button type="button" name="shop" id="shop" class="shop">vai allo shop</button>
        <p class="italic">Brand disponibile anche in boutiques</p>
    </div>
</div>

<div class="contenuto_scopri">
    <div class="testo_scopri">
        <p class="titolo">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
    </div>
    <div class="blocco1 visibile">
        <div class="immagine">
&nbsp;
        </div>
        <div class="testo">
            <h1>Burberry</h1>
            <p class="sottotitolo">SS 2015 collection</p>
            <p class="italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            <hr>
        </div>
    </div>
    <div class="blocco2 visibile">
        <div class="testo">
            <div class="cont_testo">
            <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            </div>
        </div>
        <div class="immagine">
            &nbsp;
        </div>
    </div>
    <div class="blocco3 visibile">
        <div class="immagine">
            &nbsp;
        </div>
        <div class="testo">
            <div class="cont_testo">
                <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            </div>
        </div>
    </div>
    <div class="blocco4 visibile">
        <div class="testo">
            <div class="cont_testo">
                <p>Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
        <div class="immagine">
            &nbsp;
        </div>
    </div>
    <div class="blocco5 visibile">
        <div class="immagine">
            &nbsp;
        </div>
    </div>
    <div class="blocco6 visibile">
        <div class="testo">
            <button type="button" name="shop" id="shop" class="shop">vai allo shop burberry</button>
            <p class="italic">Brand disponibile anche in boutiques</p>
        </div>
    </div>
    <div class="blocco7 visibile">
        <div class="testo">
            <div style="height:250px">&nbsp;</div>
            <p>BURBERRY.COM</p>
        </div>
    </div>
</div>




